---

# XXX npm version 6.0.1 has a bug that prevents packages from being installed.
# https://github.com/npm/npm/issues/19989
#
# remove this when the version of the package is 6.1.0 or later.
- name: Update npm to 6.1.0 which does not have a serious bug
  npm:
    name: npm
    global: yes
    state: present
    version: 6.1.0

- name: Create rc.subr script
  template:
    src: FreeBSD.rc.subr.j2
    dest: /usr/local/etc/rc.d/cncjs
    mode: 0755
    validate: sh -n %s
  notify:
    - Restart cncjs

- name: Enable cncjs
  service:
    name: cncjs
    enabled: yes
