---

# as of this writing, very few distributions have cncjs package except
# arch linux. install cncjs via npm. this might change in the future.

- include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: "install-{{ ansible_os_family }}.yml"

- name: Create cncjs group
  group:
    name: "{{ cncjs_group }}"
    state: present

- name: Create cncjs user
  user:
    name: "{{ cncjs_user }}"
    group: "{{ cncjs_group }}"
    home:  "{{ cncjs_user_home }}"
    create_home: yes
    comment: cncjs user
    state: present

- name: Create cncjs_root_dir
  file:
    path: "{{ cncjs_root_dir }}"
    owner: "{{ cncjs_user }}"
    group: "{{ cncjs_group }}"
    state: directory

- name: Install cncjs via npm under cncjs_root_dir
  npm:
    name: cncjs
    global: no
    state: present
    path: "{{ cncjs_root_dir }}"
    registry: "{{ cncjs_registry | default(omit) }}"
    version: "{{ cncjs_version | default(omit) }}"
  become: yes
  become_user: "{{ cncjs_user }}"
  environment:
    # XXX cncjs depends on serialport, which depends on gyp. gyp wants locale
    # to be set.
    # https://github.com/node-serialport/node-serialport/issues/1529
    # https://github.com/nodejs/node-gyp/issues/1283
    LANG: en_US.UTF-8
  notify:
    - Restart cncjs

- name: Create .cncrc under cncjs_user_home
  template:
    src: cncrc.j2
    dest: "{{ cncjs_conf_file }}"
    owner: "{{ cncjs_user }}"
    group: "{{ cncjs_group }}"
  notify:
    - Restart cncjs

- name: Start cncjs
  service:
    name: cncjs
    state: started
